### PR TITLE
Fix(package.json,README.md): Specify min NodeJS version (closes #3)

### LINKED ISSUE #3: Backport to node.js version 4 LTS
When using node.js < 4 the plugin cannot be loaded since the code uses ES2015 features

```
Error during loading "karma-safaritechpreview-launcher" plugin:
  /home/travis/build/litixsoft/karma-detect-browsers/node_modules/karma-safaritechpreview-launcher/index.js:11
const async = require('marcosc-async');
^^^^^
Use of const in strict mode.
```

So maybe you specify the engine property in the `package.json`:

```
"engines": {
  "node": ">=4"
}
```

so that the users will get a warning during `npm install`

Or you use es5 instead.

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@4kochi, this ok?

**Comment by 4kochi** [comment]
Yes. Great.

**Comment by 4kochi** [comment]
I will publish a new version of https://github.com/litixsoft/karma-detect-browsers when you publish the new version to npm.

**Comment by marcoscaceres** [comment]
@4kochi, just published 0.0.3. Much :heart: for karam-detect-browsers :)

**Comment by 4kochi** [comment]
Published version 2.1.0 of karma-detect-browsers

**Pull request merged**
